import { Inter } from "next/font/google";
import "./globals.css";
import "../public/bootstrap-5.3.3-dist/css/bootstrap.min.css";
import Header from "./component/header";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
        {children}
        <Footer/>
        <script src="/bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}